future: true

layout: sidebar
style: dark

repository: kairusds/kairusds.github.io

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  scope:
    path: "_posts" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 7
  exclude:
    archived: false
    forks: false
    projects:
      - treasure-chest
      - rvcd-backup
      - tModLoader
      - kairusds
      - PocketMine-MP-Android
      - js.org

social_media:
  codeberg: kairusds
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/refs/heads/main/topics/rust/rust.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/refs/heads/main/topics/javascript/javascript.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/refs/heads/main/topics/java/java.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/refs/heads/main/topics/python/python.png